fun main() {
    try {
        // code that may throw an exception
    }
    catch (e: Exception) {
        // ...
    }
    finally {
        // ...
    }
    finally {
        // ...
    }
}